import { PrismaClient, DietaryPref, MealType, BudgetTier } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding Posha database...')

  // ─── Ingredients (IFCT 2017 approximate values per 100g) ────────────────────
  const ingredients = await Promise.all([
    prisma.ingredient.upsert({
      where: { id: 'ing-toor-dal' },
      update: {},
      create: {
        id: 'ing-toor-dal',
        name: 'Toor Dal (raw)',
        nameHindi: 'तूर दाल',
        category: 'legume',
        calories: 343, protein: 22.3, carbs: 57.6, fat: 1.4, fiber: 5.3,
        iron: 5.8, calcium: 73, folate: 210, vitC: 0,
        katorEquivalentGrams: 80, commonUnit: 'katori',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-moong-dal' },
      update: {},
      create: {
        id: 'ing-moong-dal',
        name: 'Moong Dal (raw)',
        nameHindi: 'मूंग दाल',
        category: 'legume',
        calories: 347, protein: 24.0, carbs: 59.9, fat: 1.2, fiber: 4.1,
        iron: 4.4, calcium: 124, folate: 625, vitC: 3.7,
        katorEquivalentGrams: 80, commonUnit: 'katori',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-rice-cooked' },
      update: {},
      create: {
        id: 'ing-rice-cooked',
        name: 'Rice (cooked)',
        nameHindi: 'चावल (पका हुआ)',
        category: 'grain',
        calories: 130, protein: 2.7, carbs: 28.2, fat: 0.3, fiber: 0.4,
        iron: 0.2, calcium: 10, folate: 3, vitC: 0,
        katorEquivalentGrams: 150, commonUnit: 'katori',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-wheat-flour' },
      update: {},
      create: {
        id: 'ing-wheat-flour',
        name: 'Whole Wheat Flour (atta)',
        nameHindi: 'गेहूं का आटा',
        category: 'grain',
        calories: 341, protein: 12.1, carbs: 69.4, fat: 1.7, fiber: 1.9,
        iron: 3.5, calcium: 48, folate: 57, vitC: 0,
        katorEquivalentGrams: 120, commonUnit: 'katori',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-spinach' },
      update: {},
      create: {
        id: 'ing-spinach',
        name: 'Spinach (palak)',
        nameHindi: 'पालक',
        category: 'vegetable',
        calories: 26, protein: 2.0, carbs: 3.6, fat: 0.4, fiber: 0.6,
        iron: 2.7, calcium: 73, folate: 194, vitC: 28,
        katorEquivalentGrams: 100, commonUnit: 'katori',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-paneer' },
      update: {},
      create: {
        id: 'ing-paneer',
        name: 'Paneer',
        nameHindi: 'पनीर',
        category: 'dairy',
        calories: 265, protein: 18.3, carbs: 1.2, fat: 20.8, fiber: 0,
        iron: 0.2, calcium: 208, folate: 7, vitC: 0,
        katorEquivalentGrams: 80, commonUnit: 'katori',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-milk' },
      update: {},
      create: {
        id: 'ing-milk',
        name: 'Cow Milk',
        nameHindi: 'गाय का दूध',
        category: 'dairy',
        calories: 67, protein: 3.2, carbs: 4.4, fat: 4.1, fiber: 0,
        iron: 0.1, calcium: 120, folate: 5, vitC: 2,
        katorEquivalentGrams: 240, commonUnit: 'katori',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-curd' },
      update: {},
      create: {
        id: 'ing-curd',
        name: 'Curd (dahi)',
        nameHindi: 'दही',
        category: 'dairy',
        calories: 60, protein: 3.1, carbs: 4.0, fat: 3.8, fiber: 0,
        iron: 0.1, calcium: 149, folate: 7, vitC: 1,
        katorEquivalentGrams: 150, commonUnit: 'katori',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-ghee' },
      update: {},
      create: {
        id: 'ing-ghee',
        name: 'Ghee',
        nameHindi: 'घी',
        category: 'oil',
        calories: 900, protein: 0, carbs: 0, fat: 99.5, fiber: 0,
        iron: 0, calcium: 0, folate: 0, vitC: 0,
        katorEquivalentGrams: 5, commonUnit: 'tsp',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-banana' },
      update: {},
      create: {
        id: 'ing-banana',
        name: 'Banana',
        nameHindi: 'केला',
        category: 'fruit',
        calories: 89, protein: 1.1, carbs: 22.8, fat: 0.3, fiber: 2.6,
        iron: 0.3, calcium: 5, folate: 20, vitC: 8.7,
        katorEquivalentGrams: 120, commonUnit: 'piece',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-makhana' },
      update: {},
      create: {
        id: 'ing-makhana',
        name: 'Makhana (Fox Nuts)',
        nameHindi: 'मखाना',
        category: 'superfood',
        calories: 347, protein: 9.7, carbs: 76.9, fat: 0.1, fiber: 14.5,
        iron: 1.4, calcium: 60, folate: 0, vitC: 0,
        katorEquivalentGrams: 30, commonUnit: 'katori',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-ragi' },
      update: {},
      create: {
        id: 'ing-ragi',
        name: 'Ragi (Finger Millet)',
        nameHindi: 'रागी',
        category: 'grain',
        calories: 328, protein: 7.3, carbs: 72.0, fat: 1.3, fiber: 3.6,
        iron: 3.9, calcium: 344, folate: 37, vitC: 0,
        katorEquivalentGrams: 120, commonUnit: 'katori',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-bajra' },
      update: {},
      create: {
        id: 'ing-bajra',
        name: 'Bajra (Pearl Millet)',
        nameHindi: 'बाजरा',
        category: 'grain',
        calories: 361, protein: 11.6, carbs: 67.5, fat: 5.0, fiber: 1.2,
        iron: 8.0, calcium: 42, folate: 85, vitC: 0,
        katorEquivalentGrams: 120, commonUnit: 'katori',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-sattu' },
      update: {},
      create: {
        id: 'ing-sattu',
        name: 'Sattu (Roasted Chana Flour)',
        nameHindi: 'सत्तू',
        category: 'legume',
        calories: 406, protein: 20.6, carbs: 65.2, fat: 7.2, fiber: 18.6,
        iron: 9.5, calcium: 90, folate: 120, vitC: 0,
        katorEquivalentGrams: 40, commonUnit: 'katori',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-moringa' },
      update: {},
      create: {
        id: 'ing-moringa',
        name: 'Moringa Leaves (drumstick leaves)',
        nameHindi: 'सहजन के पत्ते',
        category: 'vegetable',
        calories: 64, protein: 9.4, carbs: 8.3, fat: 1.4, fiber: 2.0,
        iron: 7.0, calcium: 440, folate: 40, vitC: 220,
        katorEquivalentGrams: 50, commonUnit: 'katori',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-fenugreek-leaves' },
      update: {},
      create: {
        id: 'ing-fenugreek-leaves',
        name: 'Fenugreek Leaves (methi)',
        nameHindi: 'मेथी के पत्ते',
        category: 'vegetable',
        calories: 49, protein: 4.4, carbs: 6.0, fat: 0.9, fiber: 1.1,
        iron: 1.9, calcium: 395, folate: 57, vitC: 220,
        katorEquivalentGrams: 80, commonUnit: 'katori',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-dates' },
      update: {},
      create: {
        id: 'ing-dates',
        name: 'Dates (khajoor)',
        nameHindi: 'खजूर',
        category: 'fruit',
        calories: 282, protein: 2.5, carbs: 75.0, fat: 0.4, fiber: 8.0,
        iron: 0.9, calcium: 39, folate: 15, vitC: 0,
        katorEquivalentGrams: 40, commonUnit: 'piece',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-til' },
      update: {},
      create: {
        id: 'ing-til',
        name: 'Sesame Seeds (til)',
        nameHindi: 'तिल',
        category: 'nut',
        calories: 573, protein: 17.7, carbs: 23.5, fat: 49.7, fiber: 11.8,
        iron: 14.6, calcium: 975, folate: 97, vitC: 0,
        katorEquivalentGrams: 15, commonUnit: 'tbsp',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-chicken' },
      update: {},
      create: {
        id: 'ing-chicken',
        name: 'Chicken Breast (cooked)',
        nameHindi: 'चिकन',
        category: 'meat',
        calories: 165, protein: 31.0, carbs: 0, fat: 3.6, fiber: 0,
        iron: 1.0, calcium: 15, folate: 4, vitC: 0,
        katorEquivalentGrams: 100, commonUnit: 'katori',
      },
    }),
    prisma.ingredient.upsert({
      where: { id: 'ing-egg' },
      update: {},
      create: {
        id: 'ing-egg',
        name: 'Egg (whole)',
        nameHindi: 'अंडा',
        category: 'meat',
        calories: 155, protein: 13.0, carbs: 1.1, fat: 11.0, fiber: 0,
        iron: 1.8, calcium: 56, folate: 47, vitC: 0,
        katorEquivalentGrams: 50, commonUnit: 'piece',
      },
    }),
  ])

  console.log(`Seeded ${ingredients.length} ingredients`)

  // ─── Recipes ────────────────────────────────────────────────────────────────
  const recipes = await Promise.all([
    prisma.recipe.upsert({
      where: { id: 'rec-dal-tadka' },
      update: {},
      create: {
        id: 'rec-dal-tadka',
        name: 'Dal Tadka',
        nameHindi: 'दाल तड़का',
        description: 'Classic North Indian toor dal with smoky tempered tadka of ghee, cumin, and garlic',
        region: 'north',
        mealType: MealType.LUNCH,
        dietaryTags: [DietaryPref.VEG],
        cookTimeMinutes: 30,
        budgetTier: BudgetTier.BUDGET,
        servingGrams: 200,
        servingKatori: 1.5,
        calories: 210, protein: 12.0, carbs: 30.0, fat: 5.5, fiber: 7.0,
        iron: 4.2, calcium: 65, folate: 180,
        healthTags: ['high-protein', 'iron-rich', 'high-fiber'],
        conditionTags: ['pcos-safe', 'diabetes-friendly'],
        swapTags: ['dal-based', 'legume', 'north-indian', 'lunch-staple'],
        seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12],
        fastingSafe: false,
        pregnancySafe: true,
        postpartumRecommended: true,
      },
    }),
    prisma.recipe.upsert({
      where: { id: 'rec-jeera-rice' },
      update: {},
      create: {
        id: 'rec-jeera-rice',
        name: 'Jeera Rice',
        nameHindi: 'जीरा राइस',
        description: 'Fragrant basmati rice tempered with cumin seeds and ghee',
        region: 'north',
        mealType: MealType.LUNCH,
        dietaryTags: [DietaryPref.VEG],
        cookTimeMinutes: 20,
        budgetTier: BudgetTier.BUDGET,
        servingGrams: 180,
        servingKatori: 1.2,
        calories: 240, protein: 4.5, carbs: 48.0, fat: 4.0, fiber: 1.0,
        iron: 0.5, calcium: 12, folate: 5,
        healthTags: ['easy-to-digest'],
        conditionTags: [],
        swapTags: ['rice-dish', 'north-indian', 'lunch-staple'],
        seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12],
        fastingSafe: false,
        pregnancySafe: true,
        postpartumRecommended: false,
      },
    }),
    prisma.recipe.upsert({
      where: { id: 'rec-palak-paneer' },
      update: {},
      create: {
        id: 'rec-palak-paneer',
        name: 'Palak Paneer',
        nameHindi: 'पालक पनीर',
        description: 'Creamy spinach gravy with soft paneer cubes — iron and calcium powerhouse',
        region: 'north',
        mealType: MealType.LUNCH,
        dietaryTags: [DietaryPref.VEG],
        cookTimeMinutes: 35,
        budgetTier: BudgetTier.MODERATE,
        servingGrams: 200,
        servingKatori: 1.5,
        calories: 245, protein: 14.5, carbs: 12.0, fat: 16.0, fiber: 3.5,
        iron: 5.8, calcium: 285, folate: 210,
        healthTags: ['iron-rich', 'calcium-rich', 'high-protein'],
        conditionTags: ['pcos-safe', 'hypertension-safe'],
        swapTags: ['paneer-dish', 'greens-based', 'north-indian', 'lunch-staple'],
        seasonalMonths: [10,11,12,1,2,3],
        fastingSafe: false,
        pregnancySafe: true,
        postpartumRecommended: true,
      },
    }),
    prisma.recipe.upsert({
      where: { id: 'rec-poha' },
      update: {},
      create: {
        id: 'rec-poha',
        name: 'Poha',
        nameHindi: 'पोहा',
        description: 'Flattened rice with mustard seeds, turmeric, onion, peas — light and energizing breakfast',
        region: 'west',
        mealType: MealType.BREAKFAST,
        dietaryTags: [DietaryPref.VEG],
        cookTimeMinutes: 15,
        budgetTier: BudgetTier.BUDGET,
        servingGrams: 200,
        servingKatori: 1.5,
        calories: 250, protein: 5.5, carbs: 48.0, fat: 4.5, fiber: 2.5,
        iron: 2.8, calcium: 28, folate: 22,
        healthTags: ['iron-fortified', 'easy-to-digest', 'light'],
        conditionTags: [],
        swapTags: ['flattened-rice', 'breakfast-staple', 'west-indian'],
        seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12],
        fastingSafe: false,
        pregnancySafe: true,
        postpartumRecommended: true,
      },
    }),
    prisma.recipe.upsert({
      where: { id: 'rec-idli-sambar' },
      update: {},
      create: {
        id: 'rec-idli-sambar',
        name: 'Idli with Sambar',
        nameHindi: 'इडली सांभर',
        description: 'Steamed fermented rice-lentil cakes with tangy vegetable lentil soup — gut-friendly, protein-rich',
        region: 'south',
        mealType: MealType.BREAKFAST,
        dietaryTags: [DietaryPref.VEG],
        cookTimeMinutes: 20,
        budgetTier: BudgetTier.BUDGET,
        servingGrams: 300,
        servingKatori: 2.0,
        calories: 290, protein: 12.0, carbs: 52.0, fat: 3.5, fiber: 5.0,
        iron: 3.5, calcium: 85, folate: 95,
        healthTags: ['high-protein', 'fermented', 'gut-friendly', 'low-fat'],
        conditionTags: ['diabetes-friendly', 'pcos-safe'],
        swapTags: ['idli', 'south-indian', 'breakfast-staple', 'fermented'],
        seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12],
        fastingSafe: false,
        pregnancySafe: true,
        postpartumRecommended: true,
      },
    }),
    prisma.recipe.upsert({
      where: { id: 'rec-methi-ladoo' },
      update: {},
      create: {
        id: 'rec-methi-ladoo',
        name: 'Methi Ladoo',
        nameHindi: 'मेथी लड्डू',
        description: 'Traditional postpartum ladoo with fenugreek, dry fruits, jaggery — boosts milk supply and recovery',
        region: 'north',
        mealType: MealType.SNACK,
        dietaryTags: [DietaryPref.VEG],
        cookTimeMinutes: 45,
        budgetTier: BudgetTier.MODERATE,
        servingGrams: 60,
        servingKatori: 0.5,
        calories: 280, protein: 6.5, carbs: 32.0, fat: 14.0, fiber: 4.5,
        iron: 8.5, calcium: 180, folate: 45,
        healthTags: ['iron-rich', 'calcium-rich', 'galactagogue', 'postpartum-recovery'],
        conditionTags: [],
        swapTags: ['ladoo', 'postpartum-snack', 'north-indian'],
        seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12],
        fastingSafe: false,
        pregnancySafe: false,
        postpartumRecommended: true,
      },
    }),
    prisma.recipe.upsert({
      where: { id: 'rec-ragi-porridge' },
      update: {},
      create: {
        id: 'rec-ragi-porridge',
        name: 'Ragi Porridge',
        nameHindi: 'रागी दलिया',
        description: 'Finger millet porridge with milk, jaggery, and cardamom — calcium and iron in every bowl',
        region: 'south',
        mealType: MealType.BREAKFAST,
        dietaryTags: [DietaryPref.VEG],
        cookTimeMinutes: 15,
        budgetTier: BudgetTier.BUDGET,
        servingGrams: 250,
        servingKatori: 1.5,
        calories: 210, protein: 6.5, carbs: 42.0, fat: 3.0, fiber: 4.5,
        iron: 5.2, calcium: 420, folate: 38,
        healthTags: ['calcium-rich', 'iron-rich', 'millet'],
        conditionTags: ['diabetes-friendly', 'pcos-safe'],
        swapTags: ['porridge', 'millet-based', 'breakfast-staple', 'south-indian'],
        seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12],
        fastingSafe: false,
        pregnancySafe: true,
        postpartumRecommended: true,
      },
    }),
    prisma.recipe.upsert({
      where: { id: 'rec-sattu-drink' },
      update: {},
      create: {
        id: 'rec-sattu-drink',
        name: 'Sattu Sharbat',
        nameHindi: 'सत्तू शरबत',
        description: 'Roasted chana flour drink with lemon and black salt — high protein, cooling, iron-rich',
        region: 'north',
        mealType: MealType.DRINK,
        dietaryTags: [DietaryPref.VEG],
        cookTimeMinutes: 5,
        budgetTier: BudgetTier.BUDGET,
        servingGrams: 300,
        servingKatori: 1.5,
        calories: 165, protein: 8.5, carbs: 28.0, fat: 2.8, fiber: 7.5,
        iron: 3.8, calcium: 38, folate: 48,
        healthTags: ['high-protein', 'iron-rich', 'cooling', 'no-cook'],
        conditionTags: ['pcos-safe', 'diabetes-friendly'],
        swapTags: ['drink', 'sattu', 'north-indian', 'snack'],
        seasonalMonths: [3,4,5,6,7,8,9],
        fastingSafe: false,
        pregnancySafe: true,
        postpartumRecommended: true,
      },
    }),
    prisma.recipe.upsert({
      where: { id: 'rec-rajma' },
      update: {},
      create: {
        id: 'rec-rajma',
        name: 'Rajma',
        nameHindi: 'राजमा',
        description: 'Slow-cooked kidney beans in rich tomato-onion gravy — protein and iron staple',
        region: 'north',
        mealType: MealType.LUNCH,
        dietaryTags: [DietaryPref.VEG],
        cookTimeMinutes: 50,
        budgetTier: BudgetTier.BUDGET,
        servingGrams: 200,
        servingKatori: 1.5,
        calories: 220, protein: 13.5, carbs: 35.0, fat: 3.5, fiber: 9.0,
        iron: 5.5, calcium: 55, folate: 230,
        healthTags: ['high-protein', 'iron-rich', 'high-fiber'],
        conditionTags: ['pcos-safe'],
        swapTags: ['legume-curry', 'north-indian', 'lunch-staple'],
        seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12],
        fastingSafe: false,
        pregnancySafe: true,
        postpartumRecommended: false,
      },
    }),
    prisma.recipe.upsert({
      where: { id: 'rec-moringa-dal' },
      update: {},
      create: {
        id: 'rec-moringa-dal',
        name: 'Moringa Dal',
        nameHindi: 'सहजन दाल',
        description: 'Toor dal with drumstick leaves — pregnancy superfood, iron, calcium, and folate powerhouse',
        region: 'south',
        mealType: MealType.LUNCH,
        dietaryTags: [DietaryPref.VEG],
        cookTimeMinutes: 35,
        budgetTier: BudgetTier.BUDGET,
        servingGrams: 200,
        servingKatori: 1.5,
        calories: 195, protein: 13.0, carbs: 28.0, fat: 4.0, fiber: 6.5,
        iron: 9.5, calcium: 290, folate: 285,
        healthTags: ['iron-rich', 'calcium-rich', 'folate-rich', 'galactagogue'],
        conditionTags: ['pcos-safe'],
        swapTags: ['dal-based', 'greens-based', 'south-indian', 'pregnancy-special'],
        seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12],
        fastingSafe: false,
        pregnancySafe: true,
        postpartumRecommended: true,
      },
    }),
  ])

  console.log(`Seeded ${recipes.length} recipes`)

  // ─── Myths ──────────────────────────────────────────────────────────────────
  await Promise.all([
    prisma.myth.upsert({
      where: { id: 'myth-papaya' },
      update: {},
      create: {
        id: 'myth-papaya',
        claim: 'Eating papaya during pregnancy causes miscarriage',
        rebuttal: 'Ripe papaya is safe and nutritious. Only raw/unripe papaya contains latex (papain) which can cause uterine contractions. A ripe yellow papaya is rich in folate and Vitamin C — both important in pregnancy.',
        category: 'pregnancy',
        sources: ['AIIMS Delhi Nutrition Guidelines 2022', 'WHO Pregnancy Nutrition FAQ'],
      },
    }),
    prisma.myth.upsert({
      where: { id: 'myth-ghee-delivery' },
      update: {},
      create: {
        id: 'myth-ghee-delivery',
        claim: 'Eating large amounts of ghee lubricates the birth canal and makes delivery easier',
        rebuttal: 'There is no clinical evidence for this. Excess ghee adds saturated fat calories without benefit to delivery. Moderate ghee (1-2 tsp/day) is fine for flavor and fat-soluble vitamin absorption.',
        category: 'pregnancy',
        sources: ['FOGSI Guidelines 2021', 'NIN India Dietary Guidelines'],
      },
    }),
  ])

  console.log('Seeded myths')
  console.log('Database seeded successfully!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
